# Permalinks
#permalink:           pretty
permalink:           /blog/:year/:month/:title #changed from Poole's default to /blog/:year/:month/:day/:title then to this.

# Setup
title:               sallonoroff
tagline:             some thoughts on things made with ones and noughts
description:         some thoughts on things made with ones and noughts
lang:                en_GB
url:                 http://www.sallonoroff.co.uk
paginate:            5
paginate_path:       "/blog/page:num" #added to fix pagination issue with using /blog
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Mark Wainwright
  url:               http://www.sallonoroff.co.uk
  email:             mail@sallonoroff.co.uk
  rss_link:          http://www.sallonoroff.co.uk/blog/atom.xml
  twitter_link:      https://twitter.com/sallonoroff
  flickr_link:       https://www.flickr.com/photos/sallonoroff
  github_link:       https://github.com/sallonoroff

# Custom vars
version:             
github:
  repo:              

# Gems
gems:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap


# This is the list of pages to incldue in the header of the website for navigation
pages_list:          {'/about':'/about', '/blog':'/blog', '/blog/archive':'/blog/archive'}
