# Permalinks
#permalink:           pretty
permalink:           /blog/:year/:month/:day/:title #changed from Poole's default to this.

# Setup
title:               sallonoroff
tagline:             Some thoughts on things made with ones and noughts
description:         Some thoughts on things made with ones and noughts
url:                 www.sallonoroff.co.uk
paginate:            5
paginate_path:       "/blog/page:num" #added to fix pagination issue with using /blog
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Mark Wainwright
  url:               https://twitter.com/sallonoroff
  email:             mail@sallonoroff.co.uk

# Custom vars
version:             
github:
  repo:              

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist
  #- jekyll-sitemap

# This is the list of pages to incldue in the header of the website for navigation
pages_list:          {'About':'/about','Archive':'/blog/archive','Tags':'/blog/tags'}
